### ISSUE TITLE
[ISSUE] SCRIPT DOES NOT WORK AFTER LATEST UPDATE

### ISSUE THREAD

**Issue by marshular** [BubbleDK/bub-mdt#16]
This happens upon opening the MDT.

![LVB6JGb](https://github.com/user-attachments/assets/cb6edb0c-3603-40e8-ac38-5d07e0e325a5)

**Comment by Cocaina-Ricky** [comment]
You need to set your MDT tables to utf8mb4_general_ci. Unicode isn't supported
