### ISSUE TITLE
[Suggestion] MDT Incidents tab if possible

### ISSUE THREAD

**Issue by Cocaina-Ricky** [BubbleDK/bub-mdt#17]
Might be too much hassle but you can decline if you'd wish.

I've seen this one place else but forgot what server was using it. They utilised it very well; hope you can accomplish this too!

Allow the MDT Incident tab to where if an officer is assigned to an incident, they can add notes in realtime editing, so multiple people can edit at the same time to eliminate any down time for police. This will speed up the process of getting officers back on the roads.

**Second suggestion**
Make a template generator button so superior police ranks can create templates for different incidents with a click of a button.

For example:

```
General Incident
**SUMMARY OF WHAT HAPPENED**

**CAUTION READ?**

**ARREST NECESSITIES?**

**SEIZED ITEMS**

**EVIDENCE URL FOR BODY CAM VIDEO**

```

Then you'd have one for a traffic stop, firearms officers, etc etc.

**Comment by BubbleDK** [comment]
I probably won't be adding collab feature, but the second suggestion is on the roadmap, and will be added at some time.
