### ISSUE TITLE
Charges & Fines (Auto DB)

### ISSUE THREAD

**Issue by Deaquans** [BubbleDK/bub-mdt#25]
### The problem

Not really a problem, but a suggestion

### Ideal solution

Removal of the already implemented charges? Thereafter allow for all created fines and charges on the MDT to automatically be added to the database (so no further sql adding is needed for new charges?)

### Alternative solutions

Unsure if this is already planned, but y'know 🤷‍♂️

**Comment by BubbleDK** [comment]
If you create a charge through the mdt in-game, it'll also be added to the database. 

The `data.sql` is just some examples i've added, if people don't want to bother creating some offenses manually in-game, but you can simply just don't use them, and only create charges in-game, that'll work too.

**Comment by Deaquans** [comment]
No problem, is it possible to remove those completely? (No deleting feature yet ofcourse due to the job tags issues)

**Comment by BubbleDK** [comment]
Yes - You can just delete all the rows in the table, and go from there

**Comment by BubbleDK** [comment]
You can add as many charges to the available categorys.

**Comment by Deaquans** [comment]
Yes, but currently there's only 1 category no? I'm thinking as in a way of allowing to only do either fine or charge instead of both for special instances

(Inspired by the way redutzu does his for charges and fines)

**Comment by BubbleDK** [comment]
At the moment there's these categorys available: 

```
local chargeCategories = {
	['OFFENSES AGAINST PERSONS'] = 'Offenses Against Persons',
	['OFFENSES INVOLVING THEFT'] = 'Offenses Involving Theft',
	['OFFENSES INVOLVING FRAUD'] = 'Offenses Involving Fraud',
	['OFFENSES INVOLVING DAMAGE TO PROPERTY'] = 'Offenses Involving Damage To Property',
	['OFFENSES AGAINST PUBLIC ADMINISTRATION'] = 'Offenses Against Public Administration',
	['OFFENSES AGAINST PUBLIC ORDER'] = 'Offenses Against Public Order',
	['OFFENSES AGAINST HEALTH AND MORALS'] = 'Offenses Agaisnt Health And Morals',
	['OFFENSES AGAINST PUBLIC SAFETY'] = 'Offenses Against Public Safety',
	['OFFENSES INVOLVING THE OPERATION OF A VEHICLE'] = 'Offenses Involving The Operation Of A Vehicle',
	['OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE'] = 'Offenses Involving The Well-Being Of Wildlife',
}
```

And what you want is not possible at the moment, maybe in the future.
