### ISSUE TITLE
[Enhancement] Multijobs

### ISSUE THREAD

**Issue by ItssJxstnDe** [BubbleDK/bub-mdt#3]
You can have EMS,POLICE,FIRE,MECHANIC?
Whould be crazy

**Comment by BubbleDK** [comment]
It is out of scope for this MDT. It is only going to be available for the police. Maybe EMS will be integrated in some way, but that's not something that's being focused upon, before release.

**Comment by ItssJxstnDe** [comment]
Ok nice. Looking Definitely forward to the release!

Question: Will an Dispatch integrated INTO The Whole script or requries any Dispatch script?

**Comment by BubbleDK** [comment]
It'll be integrated into this script, so no, it's not gonna require a dispatch script.

**Comment by ItssJxstnDe** [comment]
VERY Nice hope for a release soon!

**Comment by Thirst4** [comment]
Hey really into the work you have put it so far. I currently use ps-mdt like most and would love to switch when the project is complete. I do have a question that would seal the deal. We run a multi-department with the qb-policejob and am curious if it will be similar to ps-mdt in the sense when on as LSPD it will be LSPD themed, and if I'm on as BCSO it will be BCSO themed, etc. 

Thanks!
