### ISSUE TITLE
Dashboard/mdt does not open

### ISSUE THREAD

**Issue by Mesrine67** [BubbleDK/bub-mdt#7]
![image](https://github.com/BubbleDK/bub-mdt/assets/89279156/4ae889b4-f6bb-4125-bd41-61077d22a0d1)
ESX Legacy 1.10
(Hosting) Wisp+txadmin

**Comment by eoinmcbennett** [comment]
Build the web folder

**Comment by Mesrine67** [comment]
it is not automatic?

**Comment by eoinmcbennett** [comment]
No

**Comment by Mesrine67** [comment]
how to do ? do you need a vps? or on server pterodactyl these functional? how to build the daschboard interface?

**Comment by Mesrine67** [comment]
how do I do it with a localhost server?
